extensions:
  health_check:

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681
        cors_allowed_origins:
          - '*'
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:
  backstage:
    backstage_server: 
      endpoint: http://0.0.0.0:7000
  webhook:
    traces_ingress:
      endpoint: 0.0.0.0:7070
    metrics_ingress:
      endpoint: 0.0.0.0:7071

exporters:
  logging:
  otlp:
    endpoint: ingest.lightstep.com:443
    insecure_skip_verify: true
    headers:
      "lightstep-access-token": "${LS_ACCESS_TOKEN}"

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers:
      - otlp
      processors:
      - batch
      - webhook
      exporters:
      - otlp
      - logging

    traces:
      receivers:
      - otlp
      processors: 
      - batch
      - webhook
      #- backstage
      exporters:
      - logging
      - otlp