extensions:
  health_check:

receivers:
  # Generate traces from the given topology file (env var: TOPO_FILE)
  lightstep-streams:
    organization: LightStep
    project: Robin-Hipster-Shop
    api_key: "${LIGHTSTEP_API_KEY}"
    stream_id: QQRrtJmW
  generator:
    path: "${TOPO_FILE}"
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:55681
        cors_allowed_origins:
          - '*'
      grpc:
        endpoint: 0.0.0.0:55680

processors:
  batch:
  # Annotate traces with Backstage metadata
  backstage:
    backstage_server: 
      endpoint: http://0.0.0.0:7000
  # Add/remove trace or metric attributes via webhook
  webhook:
    traces_ingress:
      endpoint: 0.0.0.0:7070
    metrics_ingress:
      endpoint: 0.0.0.0:7071

exporters:
  service:
    scraper:
      endpoint: 0.0.0.0:55688
  logging:
  # Export to Lightstep Public Satellites
  otlp:
    endpoint: "${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT}"
    insecure_skip_verify: true
    insecure: "${OTEL_INSECURE}"
    headers:
      "lightstep-access-token": "${LS_ACCESS_TOKEN}"

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers:
      - otlp
      - generator
      processors:
      - batch
      - webhook
      exporters:
      - otlp
      - logging

    traces:
      receivers:
      - otlp
      - generator
      - lightstep-streams
      processors: 
      - batch
      - webhook
      exporters:
      - logging
      - otlp
      - service